[node.accounts]
remote = "http://0.0.0.0:7799"
clone = { readonly = "programs", writable = "delegated" }
commit = { frequency_millis = 500_000, trigger = true, compute_unit_price = 1_000_000 }
create = false
